# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mann Robotics
email: mannrobo@greenvilleschools.us
description: > # this means to ignore newlines until "baseurl:"
  Mann Robotics is a Competitive Robotics Organization located at J.L. Mann High School in Greenville, SC
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mannrobo.github.io" # the base hostname & protocol for your site
twitter_username: mannrobo
github_username:  mannrobo


sass:
  style: compressed


teams:
  - name: Mann Made
    number: 3796A
    picture: /assets/teams/3796A.jpg
    short: >
      Founded four years ago during VEX Robotics Skyrise (the original team), Mann Made has since grown to a robust team of members producing capable robots.

  - name: Some Assembly Required
    number: 3796B
    picture: /assets/teams/3796B.jpg
    short: >
      Founded in VEX Robotics Nothing But Net, Some Assembly Required has been consistently able to build quality robots, and placed 13th at the South Carolina State Tournmanment in StarStruck

  - name: Don't Forget to Breathe
    number: 3796C
    picture: /assets/teams/3796C.jpg
    short: >
      Founded in VEX Robotics StarStruck, 3796C was created to attract young women to STEM and Robotics at J.L. Mann High School, and successfully competed at the State Tournament