# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mann Robotics
email: mannrobo@greenvilleschools.us
description: > # this means to ignore newlines until "baseurl:"
  Mann Robotics is a Competitive Robotics Organization located at J.L. Mann High School in Greenville, SC
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mannrobo.github.io" # the base hostname & protocol for your site
twitter_username: mannrobo
github_username:  mannrobo


sass:
  style: compressed


teams:
  - name: Mann Made
    number: 3796A
    picture: https://unsplash.it/600/600
    short: >
      Mann Made is the first team

  - name: Some Assembly Required
    number: 3796B
    picture: https://unsplash.it/600/600
    short: >
      Mann Made is the first team

  - name: Flower Power
    number: 3796C
    picture: https://unsplash.it/600/600
    short: >
      Mann Made is the first team