# Page settings
baseurl = "https://mannrobo.github.io/"
title = "Mann Robotics | Robotics Organization in Greenville, SC"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["/css/logo.css", "/css/sponsors.css", "/css/main.css"]

  # Meta
  author = "Brendan McGuire"
  description = "Mann Robotics is an VEX Robotics Competition Organization in Greenville, SC at J. L. Mann High School"
  email = "mannrobo@greenvilleschools.us"
  # Navigation
  [params.navigation]
    brand = "<img src='' alt='Mann Robotics'>"
    home = "Home"
    work = "Work"
    services = "About"
    about = "Sponsors"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Making what we love."
    subtitle = 'Mann Robotics is a VEX Robotics Competition Organization based at J. L. Mann High School in Greenville, South Carolina'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Mann Made (3796A)"
    description = "Founded three years ago during VEX Robotics Skyrise (the original team), Mann Made has since grown to a robust team of members producing capable robots."
    url = "#"
    button = "Learn More"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Some Assembly Required (3796B)"
    description = "Birthed in VEX Robotics Nothing But Net, 3796B qualified for the South Carolina State Tournament in their first year."
    url = "#"
    button = "Learn More"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "WoMann (3796C)"
    description = "Created in VEX Robotics StarStruck, 3796C was created to attract young women to STEM and Robotics at J. L. Mann High School, set to debut at the Viking Gauntlet Challenge"
    url = "#"
    button = "Learn More"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "See us in action"
    icon = "icon-play2"
    url = "https://youtube.com/watch?v=vUCbuOQSaLQ"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "About"
    description = "Starting in Vex Robotics Skyrise with only one team of 8, Mann Robotics has grown to a medium sized organization and a force to be reckoned with in the region"

    [[params.services.item]]
      title = "First Year"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-rocket"

    [[params.services.item]]
      title = "New Year, New Team"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-wrench"
    [[params.services.item]]
      title = "State Tournament"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-trophy"

      [[params.services.item]]
      title = "New Year, New Team (again)"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-people"

  # About section
  [params.about]
    enable = true
    title = "Sponsors"
    description = "Many thanks to our kind sponsors"

    [[params.about.item]]
      name = "Palmetto Partners"
      position = "Sponsor"
      description = "Palmetto Partners sponsors many robotics and STEM fields across the state of South Carolina"
      img = "sponsors/palmetto.svg"
      alt = "Person1"
      social = [
        ["icon-globe", "http://www.palmettopartnersrobotics.com/"],
      ]



  # Counters section
  [params.counters]
    enable = true
    title = "Join Now"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Teams"
      icon = "icon-people"
      from = 0
      to = 3
      interval = 2
      speed = 300

    [[params.counters.item]]
      description = "Members"
      icon = "icon-user"
      from = 0
      to = 25
      interval = 50
      speed = 300

    [[params.counters.item]]
      description = "Years Competed"
      icon = "icon-calendar"
      from = 0
      to = 3
      interval = 50
      speed = 300
    [[params.counters.item]]
      description = "Hours Spent (est.)"
      icon = "icon-clock"
      from = 0
      to = 3000
      interval = 50
      speed = 300

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "Have something to say?"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "160 Fairforest Way, <br /> Greenville, S.C. 29607"],
        ["icon-phone", "(864) 355-7581"],
        ["icon-envelope", "mannrobo@greenvilleschools.us"],
        ["icon-globe", '<a href="https://mannrobo.github.io" target="_blank">mannrobo.github.io</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Mann Robotics. All Rights Reserved.'
